import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const { teacherEmail, teacherName, courseCode, courseName, csvData } = await request.json();

    if (!teacherEmail || !csvData) {
      return NextResponse.json({ error: 'Missing required data.' }, { status: 400 });
    }

    // 1. Configure the email transporter using your environment variables
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // 2. Set up the email contents and attach the CSV file directly from memory
    const mailOptions = {
      from: `"CSE Academic Coordination" <${process.env.EMAIL_USER}>`,
      to: teacherEmail,
      subject: `Grading Roster: ${courseCode} - ${courseName}`,
      text: `Dear ${teacherName},\n\nPlease find attached the grading roster for ${courseCode} (${courseName}). \n\nPlease fill out the CT marks in the provided columns and return the CSV file to the Academic Coordinator for direct system upload.\n\nBest regards,\nDepartment of CSE\nImperial College of Engineering`,
      attachments: [
        {
          filename: `${courseCode}_Grading_Sheet.csv`,
          content: csvData, // The raw CSV text generated by the frontend
        },
      ],
    };

    // 3. Send the email
    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true, message: `Email successfully sent to ${teacherEmail}` }, { status: 200 });
  } catch (error: any) {
    console.error('Email error:', error);
    return NextResponse.json({ error: 'Failed to send email. Check your SMTP credentials.' }, { status: 500 });
  }
}